---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-notification-controller
spec:
  vars:
    - name: srcPath
    - name: targetRing

  steps:
    - uses: kustomize-set-image
      as: update-image
      config:
        path: ${{ vars.srcPath }}/components/notification-controller-rd/rings/${{ vars.targetRing }}/base
        images:
          - image: quay.io/konflux-ci/notification-service
            newName: quay.io/konflux-ci/notification-service
            newTag: ${{ imageFrom("quay.io/konflux-ci/notification-service").Tag }}

    - uses: yaml-update
      as: update-external-ref
      config:
        path: ${{ vars.srcPath }}/components/notification-controller-rd/rings/${{ vars.targetRing }}/base/kustomization.yaml
        updates:
          - key: resources.0
            value: https://github.com/konflux-ci/notification-service/config/default?ref=${{ imageFrom("quay.io/konflux-ci/notification-service").Tag }}
