---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: notification-controller
spec:
  freightCreationPolicy: Automatic
  interval: 30m0s
  subscriptions:
    - image:
        repoURL: quay.io/konflux-ci/notification-service
        imageSelectionStrategy: NewestBuild
        discoveryLimit: 5
        allowTagsRegexes:
          - ^[0-9a-f]{40}$
