---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-app-reader
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-app-reader-token
  labels:
    kargo.akuity.io/cred-type: generic
  annotations:
    kubernetes.io/service-account.name: argocd-app-reader
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-konflux-core-argocd-app-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-argocd-app-reader
subjects:
  - kind: ServiceAccount
    name: argocd-app-reader
    namespace: kargo-konflux-core
