apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd.yaml
  - ns.yaml
  # Wait until we have stopped the sync in ALL AppSRE-hosted Argo CD instances
  # - all-application-sets-app.yaml
