---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-app-reader
  namespace: kargo-shared-resources
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-app-reader-token
  namespace: kargo-shared-resources
  labels:
    kargo.akuity.io/cred-type: generic
  annotations:
    kubernetes.io/service-account.name: argocd-app-reader
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-infra-common-argocd-app-reader
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-infra-common-argocd-app-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-infra-common-argocd-app-reader
subjects:
  - kind: ServiceAccount
    name: argocd-app-reader
    namespace: kargo-shared-resources
