apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/flacatus/konflux-dummy-deploy//k8s?ref=ad75e2db900cde4625558a0cbf8265cac8342443
images:
  - name: quay.io/redhat-appstudio-qe/dummy-deployment
    newTag: ad75e2db900cde4625558a0cbf8265cac8342443
patches:
  - target:
      kind: ConfigMap
      name: dummy-deployment-config
    patch: |
      - op: replace
        path: /data/DISPLAY_TEXT
        value: "Hello from EXTERNAL STAGING!"
