---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kargo-rhobs-production
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: production/devprod/kargo-rhobs-production
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: kargo-rhobs-production
    template:
      metadata:
        annotations:
          kargo.akuity.io/replicate-to: "*"
        labels:
          kargo.akuity.io/cred-type: generic
