apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-kube-state-metrics-config
  namespace: appstudio-monitoring
data:
  custom-resource-state.yaml: |
    spec:
      resources:
        ###############################################################################
        # Kargo Stages
        ###############################################################################
        - groupVersionKind:
            group: "kargo.akuity.io"
            version: "v1alpha1"
            kind: "Stage"
          labelsFromPath:
            stage: [metadata, name]
            namespace: [metadata, namespace]
          metrics:
            - name: "kargo_stage_health_status"
              help: "Current health status of the Kargo Stage"
              each:
                type: StateSet
                stateSet:
                  labelName: health
                  path: [status, health, status]
                  list: [Healthy, Unhealthy, Unknown, NotApplicable, Progressing]

            - name: "kargo_stage_last_promotion_phase"
              help: "Phase of the latest Kargo Promotion for the Stage"
              each:
                type: StateSet
                stateSet:
                  labelName: phase
                  path: [status, lastPromotion, status, phase]
                  list: [Pending, Running, Succeeded, Failed, Errored, Aborted]

            - name: "kargo_stage_last_promotion_started_timestamp"
              help: "Start timestamp of the latest Kargo Promotion"
              each:
                type: Gauge
                gauge:
                  path: [status, lastPromotion, status, startedAt]
                  nilIsZero: false

            - name: "kargo_stage_last_promotion_finished_timestamp"
              help: "Finish timestamp of the latest Kargo Promotion"
              each:
                type: Gauge
                gauge:
                  path: [status, lastPromotion, status, finishedAt]
                  nilIsZero: false
        ###############################################################################
        # Kargo Warehouses
        ###############################################################################
        - groupVersionKind:
            group: "kargo.akuity.io"
            version: "v1alpha1"
            kind: "Warehouse"
          labelsFromPath:
            warehouse: [metadata, name]
            namespace: [metadata, namespace]
          metrics:
            - name: "kargo_warehouse_condition"
              help: "Current condition status of the Kargo Warehouse"
              each:
                type: Gauge
                gauge:
                  path: [status, conditions]
                  labelsFromPath:
                    condition: [type]
                  valueFrom: [status]
