---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - clusterrolebinding.yaml
  - secret.yaml
  - namespace.yaml
  - lease-rbac.yaml
  - project-rbac.yaml
  - external-secret.yaml
  - infra-deployments/staging
