---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-shard-staging
  namespace: kargo-infra-common
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-shard-staging
  namespace: kargo-infra-common
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-shard-staging
subjects:
  - kind: ServiceAccount
    name: kargo-shard-staging
    namespace: kargo
