---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ring-1-dummy-deployment
  labels:
    konflux-environment: staging
  annotations:
    kargo.akuity.io/color: yellow
spec:
  shard: infra-deployments-staging
  requestedFreight:
    - origin:
        kind: Warehouse
        name: dummy-deployment
      sources:
        stages:
          - ring-0-dummy-deployment
  verification:
    analysisTemplates:
      - name: kanary-staging
      - name: konflux-conformance-tests-stone-stage-p01
    args:
      - name: clusters
        value: stone-stg-rh01|stone-stage-p01
      - name: expected-cluster-count
        value: "2"
  promotionTemplate:
    spec:
      vars:
        - name: srcPath
          value: ./src
        - name: repoURL
          value: https://github.com/redhat-appstudio/infra-deployments.git
        - name: component
          value: ${{ ctx.targetFreight.origin.name }}
        - name: targetRing
          value: ring-1
      steps:
        - uses: git-clone
          as: clone
          config:
            repoURL: ${{ vars.repoURL }}
            checkout:
              - branch: main
                path: ${{ vars.srcPath }}
        - task:
            name: dummy-deployment-promote-ring-1
          as: promote
          vars:
            - name: srcPath
              value: ${{ vars.srcPath }}
        - uses: git-commit
          as: commit
          config:
            path: ${{ vars.srcPath }}
            message: |
              chore(${{ ctx.stage }}): promote ${{ vars.component }} to ${{ vars.targetRing }}
        - uses: compose-output
          as: set-promotion-as-no-op
          config:
            promotionAsNoOp: "${{ status('commit') == 'Skipped' ? 'yes' : 'no' }}"
        - task:
            name: git-workflow-infra-deployments
          as: workflow
          vars:
            - name: srcPath
              value: ${{ vars.srcPath }}
            - name: repoURL
              value: ${{ vars.repoURL }}
            - name: component
              value: ${{ vars.component }}
            - name: targetRing
              value: ${{ vars.targetRing }}
            - name: promotionAsNoOp
              value: "${{ outputs['set-promotion-as-no-op'].promotionAsNoOp }}"
            - name: skipProwChecks
              value: "true"
            - name: clusters
              value: "stone-stg-rh01|stone-stage-p01"
            - name: tokenSecret
              value: argocd-app-reader-token-staging
