apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../all-application-sets/ring-2
  - ../all-application-sets/ring-3
  - ../all-application-sets/ring-4
  - external-secrets

patches:
    - path: patches/argocd-controller-replicas-patch.yaml
      target:
        group: argoproj.io
        version: v1beta1
        kind: ArgoCD
