---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ring-0-etcd-defrag
  labels:
    konflux-environment: development
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: etcd-defrag-manifest-wh
      sources:
        direct: true
    - origin:
        kind: Warehouse
        name: etcd-defrag-image-wh
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: compose-output
          as: passthrough
          config:
            status: skipped
