---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: codecov
resources:
  - ../base
  - external-secrets
  - storage.yaml
  - infra.yaml
  - codecov.yaml
  - route.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "-1"
