---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kargo-shard-infra-common-deployments
spec:
  generators:
    - clusters:
        values:
          sourceRoot: components/kargo-shard
          environment: ""
  template:
    metadata:
      name: kargo-shard-infra-common-deployments-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/infra-common-deployments'
        repoURL: https://github.com/redhat-appstudio/infra-common-deployments.git
        targetRevision: main
      destination:
        namespace: kargo-shard-infra-common-deployments
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
