---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - project.yaml
  - project-config.yaml
  - rbac
  - external-secrets
  - promotion-tasks
  - analysis-templates
  - ../../../kargo-shared-verifications/konflux-conformance-tests
  - stages
