---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-infra-deployments
spec:
  promotionPolicies:
    - stage: ring-0-konflux-operator
      autoPromotionEnabled: true
    - stage: ring-0-dummy-deployment
      autoPromotionEnabled: true
    - stage: ring-1
      autoPromotionEnabled: true
