---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-infra-deployments
spec:
  promotionPolicies:
    - stage: ring-0-konflux-operator
      autoPromotionEnabled: true
    - stage: ring-0-dummy-deployment
      autoPromotionEnabled: true
    - stage: ring-1
      autoPromotionEnabled: true
    - stage: ring-2
      autoPromotionEnabled: true
    - stage: ring-3
      autoPromotionEnabled: true
    - stage: ring-4
      autoPromotionEnabled: true
