---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- internal-services.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "11"

# namespace: DO NOT USE THIS FIELD, this allows us to create localqueues for components in more than one namespace
