apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-infra-deployments

resources:
  - stg-rh01-es.yaml
  - stg-es01-es.yaml
  - stg-p01-es.yaml
  - redhat-appstudio-es.yaml
