---
# External Secret for n8n credentials
# This will sync secrets from Vault to Kubernetes
# JIRA: DPROD-1141
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n-secrets
  namespace: konflux-devlake
  labels:
    app: n8n
spec:
  # Use the same secret store as DevLake
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault

  # Target Kubernetes secret that will be created
  target:
    name: n8n-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # n8n encryption key for credentials storage
        encryption-key: "{{ .encryptionKey }}"

        # Basic auth for n8n UI
        basic-auth-user: "{{ .basicAuthUser }}"
        basic-auth-password: "{{ .basicAuthPassword }}"

        # PostgreSQL database for n8n internal storage
        # (Separate from DevLake MySQL - n8n needs its own DB)
        n8n-db-host: "{{ .n8nDbHost }}"
        n8n-db-port: "{{ .n8nDbPort | default \"5432\" }}"
        n8n-db-database: "{{ .n8nDbDatabase | default \"n8n\" }}"
        n8n-db-user: "{{ .n8nDbUser }}"
        n8n-db-password: "{{ .n8nDbPassword }}"

        # DevLake MySQL credentials (for workflow queries)
        # These will be added as credentials IN n8n UI manually
        # but keeping them here for reference
        devlake-mysql-host: "{{ .devlakeMysqlHost }}"
        devlake-mysql-port: "{{ .devlakeMysqlPort | default \"3306\" }}"
        devlake-mysql-database: "{{ .devlakeMysqlDatabase | default \"lake\" }}"
        devlake-mysql-user: "{{ .devlakeMysqlUser }}"
        devlake-mysql-password: "{{ .devlakeMysqlPassword }}"

  # Data to extract from Vault
  dataFrom:
  - extract:
      # Path in Vault where n8n secrets are stored
      # This path is under stonesoup/data/production/devprod/ (devprod team vault)
      key: stonesoup/data/production/devprod/n8n

  # Refresh interval - check Vault every 1 hour for secret updates
  refreshInterval: 1h
