---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: hello-world
spec:
  metrics:
    - name: hello
      count: 1
      failureLimit: 0
      provider:
        job:
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - name: hello
                    image: alpine:3.19
                    command:
                      - echo
                      - "Hello World"
                restartPolicy: Never
