apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rover-group-sync
resources:
  - ../base
patches:
  - path: cronjob-patch.yaml
    target:
      kind: CronJob
      name: rover-group-sync
  - path: externalsecrets-patch.yaml
