apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rover-group-sync

images:
- name: quay.io/redhat-user-workloads/konflux-infra-tenant/rover-group-sync
  newName: quay.io/redhat-user-workloads/konflux-infra-tenant/rover-group-sync
  digest: sha256:45325f6ec0d064ceaa4ecd8fa17958394592f9bb3c5f95d0d5167e218bae94f0

resources:
  - ../base

patches:
  - path: cronjob-patch.yaml
    target:
      kind: CronJob
      name: rover-group-sync
  - path: externalsecrets-patch.yaml
