apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rover-group-sync

images:
- name: quay.io/redhat-user-workloads/konflux-infra-tenant/rover-group-sync
  newName: quay.io/redhat-user-workloads/konflux-infra-tenant/rover-group-sync
  digest: sha256:0943b55b7d170a859a5bd9847a504a4b720084b0abdbf6eee3ef2c12ee70bbbc

resources:
- namespace.yaml
- ibmid
- rh-sso-internal
