---
# Credentials required to execute the Konflux conformance test suite from
# github.com/konflux-ci/konflux-ci. Synced from Vault path
# production/devprod/konflux-conformance-tests-credentials.
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: konflux-conformance-tests-credentials
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - extract:
        key: production/devprod/konflux-conformance-tests-credentials
        decodingStrategy: None
  refreshInterval: 10m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: konflux-conformance-tests-credentials
    template:
      metadata:
        annotations:
          kargo.akuity.io/replicate-to: "*"
        labels:
          kargo.akuity.io/cred-type: generic
