---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: internal-services
resources:
  # Core resources now managed directly in production
  - crds/
  - eso/
  - cronjob/

  # External Secrets
  - es/
  # InternalServicesConfig
  - config/
  # Manager deployments
  - manager/
  # NetworkPolicy
  - networkpolicy/
  # RBAC Resources
  - rbac/
  # Signing ConfigMaps
  - signing/
