---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-helm
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - chart:
        repoURL: oci://ghcr.io/akuity/kargo-charts
        name: kargo
        semverConstraint: ^1.10.0
        discoveryLimit: 5
