---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: wait-for-ci
spec:
  vars:
    - name: commitSHA
    - name: repoOwner
      value: redhat-appstudio
    - name: repoName
      value: infra-deployments
    - name: requiredChecks
      value: ""
  steps:
    - uses: http
      as: wait-for-check-runs
      retry:
        timeout: 2h30m
      config:
        method: GET
        url: https://api.github.com/repos/${{ vars.repoOwner }}/${{ vars.repoName }}/commits/${{ vars.commitSHA }}/check-runs
        headers:
          - name: Authorization
            value: Bearer ${{ secret('kargo-infra-deployments-secrets').github_pat }}
          - name: Accept
            value: application/vnd.github+json
        successExpression: |
          response.status == 200 &&
          len(filter(response.body.check_runs, {vars.requiredChecks == '' ? true : (.name matches '${{ vars.requiredChecks }}')})) > 0 &&
          all(filter(response.body.check_runs, {vars.requiredChecks == '' ? true : (.name matches '${{ vars.requiredChecks }}')}), {.conclusion == 'success'})
        timeout: 30s
    - uses: http
      as: wait-for-prow-checks
      retry:
        timeout: 2h30m
      config:
        method: GET
        url: https://api.github.com/repos/${{ vars.repoOwner }}/${{ vars.repoName }}/commits/${{ vars.commitSHA }}/status
        headers:
          - name: Authorization
            value: Bearer ${{ secret('kargo-infra-deployments-secrets').github_pat }}
          - name: Accept
            value: application/vnd.github+json
        successExpression: |
          response.status == 200 &&
          len(filter(response.body.statuses, {.context != 'tide' && (vars.requiredChecks == '' ? true : (.context matches '${{ vars.requiredChecks }}'))})) > 0 &&
          all(filter(response.body.statuses, {.context != 'tide' && (vars.requiredChecks == '' ? true : (.context matches '${{ vars.requiredChecks }}'))}), {.state == 'success'})
        timeout: 30s
