apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gh-argocd-appstudio-externalsecret.yaml
  - https://github.com/redhat-appstudio/internal-infra-deployments.git/components/k8s-groups/staging/rover?ref=latest
  
namespace: k8s-groups
