---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: production-kargo-kubeconfig
  namespace: kargo-shard-infra-deployments
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: production-kargo-kubeconfig
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: staging/devprod/kargo-shard-kubeconfig
