queueName: pipelines-queue
cel:
  expressions:
    - |
        has(pipelineRun.metadata.labels) &&
        'internal-services.appstudio.openshift.io/pipelinerun-uid' in pipelineRun.metadata.labels ?
        priority('konflux-release') :
        priority('konflux-default')
