apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Core resources now managed directly in staging
  - crds/
  - eso/
  - cronjob/

  # Manager deployments for staging
  - manager/

  # Network Policy
  - networkpolicy/

  # RBAC Resources
  - rbac/

  # InternalServicesConfig
  - config/

  # External Secrets
  - es/

  # Signing configurations
  - signing/
