---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: konflux-support-ops-secrets-prod
  namespace: konflux-support-ops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: production/support-ops/konflux-support-ops-secrets
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: konflux-support-ops-secrets
