apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: konflux-public-production

resources:
  - ../base
  - ns.yaml

patches:
  - path: patches/argocd-controller-sharding-replica-patch.yaml
    target:
      group: argoproj.io
      version: v1beta1
      kind: ArgoCD
  - path: patches/source-path-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: argocd-external-appsre-all-application-sets
  - path: patches/destination-namespace-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: argocd-external-appsre-all-application-sets
