apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kargo
name: kargo
repo: oci://ghcr.io/akuity/kargo-charts
version: 1.10.7
namespace: kargo
releaseName: kargo
valuesInline:
  image:
    repository: quay.io/konflux-ci/kargo
    tag: 1.10-2cd30bc
  api:
    adminAccount:
      enabled: false
    secretManagementEnabled: false
    tls:
      selfSignedCert: false
    host: kargo-api-kargo.apps.rosa.kflux-c-prd-i01.7hyu.p3.openshiftapps.com
    cabundle:
      configMapName: ocp-service-ca
    oidc:
      enabled: true
      admins:
        claims:
          groups:
          - konflux-admins
          - cluster-admins
          - dedicated-admins
          - konflux-infra
          - konflux-devprod
      dex:
        enabled: true
        image:
          repository: quay.io/konflux-ci/dex
          tag: d0a57c362345f65484540f7e3bee2e330d7e3c68
        skipApprovalScreen: true
        tls:
          selfSignedCert: false
        connectors:
          - type: openshift
            id: openshift
            name: OpenShift
            config:
              issuer: https://kubernetes.default.svc
              rootCA: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              clientID: system:serviceaccount:kargo:dex-client
              clientSecret: $OPENSHIFT_OAUTH_CLIENT_SECRET
              redirectURI: https://kargo-api-kargo.apps.rosa.kflux-c-prd-i01.7hyu.p3.openshiftapps.com/dex/callback
        env:
          - name: OPENSHIFT_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dex-client
                key: token
