---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kargo-infra-deployments

resources:
  - base
  - dummy-deployment
  - konflux-operator
  - authentication

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
