apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: konflux-support-ops

resources:
- ../base
- external-secrets

patches:
- target:
    kind: Deployment
    name: support-ops
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: support-ops
    spec:
      replicas: 0
