apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
spec:
  generators:
    - clusters:
        values:
          sourceRoot: components/kyverno
          environment: ""
  template:
    metadata:
      name: kyverno-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}'
        repoURL: https://github.com/redhat-appstudio/infra-common-deployments.git
        targetRevision: main
      destination:
        namespace: konflux-kyverno
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 50
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
