---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: codecov-quota
  namespace: codecov
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 6Gi
    limits.cpu: "6"
    limits.memory: 6Gi
    persistentvolumeclaims: "4"
    requests.storage: 40Gi
