apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - analysistemplate.yaml
  - analysistemplate-production.yaml
configMapGenerator:
  - name: caching-proxy-regression-runner
    files:
      - run.sh
      - pipelinerun.yaml
generatorOptions:
  disableNameSuffixHash: true
