apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rover-group-sync

images:
- name: quay.io/redhat-user-workloads/konflux-infra-tenant/rover-group-sync
  newName: quay.io/redhat-user-workloads/konflux-infra-tenant/rover-group-sync
  digest: sha256:11682fb548b706a58b64cb6b3c37fbe274f89af6ef58c3423ce7af696ee603ba

resources:
  - ../base
