apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rover-group-sync

images:
- name: rover-group-sync
  digest: sha256:a0c5c759213f0a9242da4dfeb7ab7536d7db032ddb96acfe09d4347638173e05

resources:
  - ../base
