---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-authentication-manifests
spec:
  vars:
    - name: srcPath
    - name: component
    - name: prevRing
    - name: targetRing

  steps:
    # Copies the tier 1 base directory to the target ring's base-snapshot directory; only happens when promoting from base
    - uses: copy
      as: copy-tier-1-folder
      if: ${{ ctx.targetFreight.origin.name == vars.component + "-manifest-wh" && vars.prevRing == "base" }}
      config:
        inPath: ${{ vars.srcPath }}/components/${{ vars.component }}/base
        outPath: ${{ vars.srcPath }}/components/${{ vars.component }}/rings/${{ vars.targetRing }}/base/base-snapshot

    # Copies the previous ring's base-snapshot directory to the target ring's base-snapshot directory
    - uses: copy
      as: copy-prev-ring-base-snapshot-folder
      if: ${{ ctx.targetFreight.origin.name == vars.component + "-manifest-wh" && vars.prevRing != "base" }}
      config:
        inPath: ${{ vars.srcPath }}/components/${{ vars.component }}/rings/${{ vars.prevRing }}/base/base-snapshot
        outPath: ${{ vars.srcPath }}/components/${{ vars.component }}/rings/${{ vars.targetRing }}/base/base-snapshot
