---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: authentication-manifest-wh
spec:
  freightCreationPolicy: Automatic
  interval: 2h0m0s
  subscriptions:
  - git:
      repoURL: https://github.com/redhat-appstudio/infra-deployments.git
      commitSelectionStrategy: NewestFromBranch
      branch: main
      includePaths:
        - 'components/authentication/new-base'
