---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: konflux-kargo-git-operations
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: production/devprod/konflux-kargo-git-operations
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: konflux-kargo-git-operations
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: generic
