---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kargo-shared-resources

resources:
  - kargo-promotion-credentials.yaml
  - argocd-app-reader-token-staging.yaml
  - kargo-rhobs-credentials
  - konflux-verifications-credentials
