---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-admission:viewer-egressfirewall
  labels:
    rbac.kyverno.io/aggregate-to-admission-controller: "true"
rules:
- apiGroups:
  - k8s.ovn.org
  resources:
  - egressfirewalls
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-background:manage-egressfirewall
  labels:
    rbac.kyverno.io/aggregate-to-background-controller: "true"
rules:
- apiGroups:
  - k8s.ovn.org
  resources:
  - egressfirewalls
  verbs:
  - create
  - get
  - list
  - delete
  - update
