---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kargo-shard-infra-deployments-production-leases
  namespace: kargo-shard-infra-deployments-production
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
