---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: ring-2-promote
spec:
  vars:
    - name: srcPath
    - name: component
  steps:
    - uses: yaml-update
      as: update-kargo
      if: ${{ vars.component == "kargo" }}
      config:
        path: ${{ vars.srcPath }}/components/kargo/internal-production/deployment/kargo-helm-generator.yaml
        updates:
          - key: version
            value: ${{ chartFrom("oci://ghcr.io/akuity/kargo-charts/kargo").Version }}
          - key: valuesInline.image.tag
            value: ${{ imageFrom("quay.io/konflux-ci/kargo").Tag }}
          - key: valuesInline.api.oidc.dex.image.tag
            value: ${{ imageFrom("quay.io/konflux-ci/dex").Tag }}
