---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kyverno-source-token
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  # GitHub installation tokens expire after one hour.
  refreshInterval: 15m
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: kyverno-source-token
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: kyverno-source-token
    template:
      engineVersion: v2
      metadata:
        labels:
          kargo.akuity.io/cred-type: generic
      data:
        token: "{{ .token }}"
