---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: konflux-devlake
spec:
  template:
    spec:
      containers:
        - name: oauth2-proxy
          env:
            - name: OAUTH2_PROXY_SKIP_AUTH_ROUTES
              value: "^/grafana/.*,^/health.*,^/api/rest/plugins/webhook/.*"
            - name: OAUTH2_PROXY_SKIP_JWT_BEARER_TOKENS
              value: "true"
            - name: OAUTH2_PROXY_EXTRA_JWT_ISSUERS
              value: "https://sso.redhat.com/auth/realms/redhat-external=cloud-services"
            - name: OAUTH2_PROXY_BEARER_TOKEN_LOGIN_FALLBACK
              value: "false"
            - name: OAUTH2_PROXY_API_ROUTES
              value: "^/api/"
