---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: cluster-name-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
  - path: environment-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
