---
apiVersion: v1
kind: Secret
metadata:
  name: kargo-shard-staging-token
  namespace: kargo
  annotations:
    kubernetes.io/service-account.name: kargo-shard-staging
type: kubernetes.io/service-account-token
