apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - path: monitoringstack-patch.yaml
    target:
      kind: MonitoringStack
      name: appstudio-federate-ms
  - path: rhobs-external-secret-patch.yaml
    target:
      kind: ExternalSecret
      name: rhobs
