- op: replace
  path: /spec/logLevel
  value: debug
- op: replace
  path: /spec/resources/requests/cpu
  value: 100m
- op: replace
  path: /spec/resources/requests/memory
  value: 2Gi
- op: replace
  path: /spec/resources/limits/memory
  value: 2Gi
- op: replace
  path: /spec/prometheusConfig/externalLabels/source_environment
  value: staging
- op: replace
  path: /spec/prometheusConfig/externalLabels/source_cluster
  value: kflux-c-stg-e01
- op: replace
  path: /spec/prometheusConfig/replicas
  value: 1
- op: replace
  path: /spec/prometheusConfig/remoteWrite/0/oauth2/endpointParams/audience
  value: observatorium-osd-staging
- op: replace
  path: /spec/prometheusConfig/remoteWrite/0/url
  value: https://observatorium-mst.api.stage.openshift.com/api/metrics/v1/rhtap/api/v1/receive
