---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ring-0-notification-controller
  labels:
    konflux-environment: development
  annotations:
    kargo.akuity.io/color: blue
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: notification-controller
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: compose-output
          as: passthrough
