---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - spre-automations-viewers.yaml
  - pharos-reader-serviceaccount.yaml
  - pharos-reader-clusterrole.yaml
  - pharos-reader-clusterrolebinding.yaml
