---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konflux-mcp-server
  namespace: konflux-devlake
spec:
  template:
    spec:
      containers:
        - name: mcp-server
          env:
            - name: DB_SSL
              value: "false"
