---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kargo-konflux-infrastructure

resources:
  - base
  - components/cluster-secret-store
  - components/authentication
  - components/etcd-defrag
  - components/etcd-shield
  - components/external-secrets-operator
  - components/kueue
  - components/kyverno
  - components/multi-platform-controller
  - components/policies
  - components/repository-validator
  - components/cluster-secret-store-rh

components:
  - ../../shared/promotion-tasks
  - ../../shared/verifications

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
