---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: rover-group-sync
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - image:
        repoURL: quay.io/redhat-user-workloads/konflux-infra-tenant/rover-group-sync
        imageSelectionStrategy: NewestBuild
        discoveryLimit: 5
        allowTags: ^[0-9a-f]{40}$
