---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - project.yaml
  - project-config.yaml
  - rbac
  - external-secrets
  - stage-ring-1-staging.yaml
  - stage-ring-2-production.yaml
