---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-infra-common
spec:
  promotionPolicies:
    - stage: ring-1-staging
      autoPromotionEnabled: false
    - stage: ring-2-production
      autoPromotionEnabled: false
