---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: ring-1-staging
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: repoURL
          value: https://github.com/redhat-appstudio/infra-common-deployments.git
        - name: component
          value: ${{ ctx.targetFreight.origin.name }}
      steps:
        - uses: git-clone
          as: clone
          config:
            repoURL: ${{ vars.repoURL }}
            checkout:
              - branch: main
                path: ./src
        - task:
            name: ring-1-promote
          as: promote
          vars:
            - name: srcPath
              value: ./src
            - name: component
              value: ${{ vars.component }}
        - uses: git-commit
          as: commit
          config:
            path: ./src
            message: |
              chore(${{ ctx.stage }}): promote ${{ vars.component }}
        - uses: git-push
          as: push
          config:
            path: ./src
            targetBranch: ${{ ctx.project }}/${{ vars.component }}/ring-1-staging
            force: true
        - uses: git-open-pr
          as: open-pr
          continueOnError: true
          config:
            repoURL: ${{ vars.repoURL }}
            sourceBranch: ${{ ctx.project }}/${{ vars.component }}/ring-1-staging
            targetBranch: main
            title: "chore(${{ ctx.stage }}): promote ${{ vars.component }} to staging"
            labels:
              - ring-1
              - staging
              - automated-promotion
              - component/${{ vars.component }}
        - uses: git-wait-for-pr
          if: ${{ status('open-pr') != 'Errored' }}
          as: wait-for-pr
          config:
            repoURL: ${{ vars.repoURL }}
            prNumber: ${{ outputs['open-pr'].pr.id }}
