apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kargo-infra-common
  - kargo-infra-deployments

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
