apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
components:
  - ../k-components/staging
  - ../k-components/internal-federation
patches:
  - target:
      kind: MonitoringStack
      name: appstudio-federate-ms
    patch: |-
      - op: replace
        path: /spec/prometheusConfig/externalLabels/source_cluster
        value: kflux-c-stg-i01
