---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-internal-requests-pipelineruns
spec:
  schedule: "10 03 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600 # 1h
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: controller-manager
          volumes:
            - name: temp-directory
              emptyDir: {}
          containers:
            - name: cr-cleanup
              env:
                - name: CR_TYPE
                  value: "pipelinerun"
                - name: CR_NAMESPACE
                  value: "internal-services"
                - name: OLDER_THAN
                  value: "yesterday"
                - name: LABELS
                  value: "pipelines.appstudio.openshift.io/type=release"
              command:
                - /bin/bash
                - -c
                - |
                  set -o pipefail
                  PATH="/bin:/usr/bin:/usr/local/bin"
                  PRUNING_CRS_FILE="/var/tmp/crs-to-be-pruned"
                  KUBECTL_OUTPUT=$(mktemp -p /var/tmp)
                  SECONDS_BACK=$(date -d "${OLDER_THAN}" +%s)

                  if ! kubectl get "${CR_TYPE}" -n "${CR_NAMESPACE}" -l "${LABELS}" \
                  --timeout=30s \
                  --template '{{range .items}}{{if .status.completionTime}}{{.metadata.name}}{{"\t"}}{{.metadata.namespace}}{{"\t"}}{{.status.completionTime}}{{"\n"}}{{end}}{{end}}' > $KUBECTL_OUTPUT; then
                    echo "ERROR: failed to list ${CR_TYPE} resources"
                    exit 1
                  fi

                  awk -v since=${SECONDS_BACK} '{
                       # parsing the completionTime and converting it to epoch
                       # so we can compute the precise CRs that should be deleted
                       gsub("[:\\-TZ]", " ", $3)
                       t=mktime($3)
                       completionTime=strftime("%s", t)
                       #
                       # completionTime should be smaller than `since` seconds so it can be deleted
                       if(since > completionTime) {
                         args="%s:%s\n"
                         printf(args, $1, $2)
                       }
                    }' $KUBECTL_OUTPUT > $PRUNING_CRS_FILE

                  while IFS= read -r line; do
                    cr=${line%:*}
                    namespace=${line#*:}
                    if output=$(kubectl delete "${CR_TYPE}" "${cr}" -n "${namespace}" --wait=false --timeout=30s 2>&1); then
                      echo "INFO: namespace=${namespace} ${output}"
                    else
                      echo "ERROR: namespace=${namespace} ${output}"
                    fi
                  done < $PRUNING_CRS_FILE
              imagePullPolicy: IfNotPresent
              image: quay.io/konflux-ci/release-service-utils:9089cafbf36bb889b4b73d8c2965613810f13736
              volumeMounts:
                - mountPath: /var/tmp
                  name: temp-directory
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 200m
                  memory: 256Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
