---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kargo-konflux-monitoring

resources:
  - base

components:
  - ../../kargo-shared-promotion-tasks
  - ../../kargo-shared-verifications

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
