---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: segment-write-key
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: staging/service-enhancement/segment-write-key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    name: segment-write-key
    creationPolicy: Owner
    deletionPolicy: Delete
