---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-queue.yaml
- local-queue.yaml
- workload-priority-class.yaml
commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"
