apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd-infra-deployments

resources:
  - prd-p01-es.yaml
  - prd-p02-es.yaml
  - prd-rh01-es.yaml
  - prd-rh02-es.yaml
  - prd-rh03-es.yaml
  - prd-es01-es.yaml
  - ocp-p01-es.yaml
  - rhel-p01-es.yaml
  - osp-p01-es.yaml
  - fedora-01-es.yaml
  - redhat-appstudio-es.yaml
