---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: iib-qe

resources:
- namespace.yaml
- iib-qe-maintainers.yaml
- serviceaccount.yaml
- trusted-ca-configmap.yaml
- repositories
- registry-proxy-push-secret.yaml
- registry-redhat-io-read.yaml
- gitlab-webhook-config.yaml
- gitlab-git-auth.yaml
