---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: registry-redhat-io-read
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: staging/operator-foundry/iib-qe/registry-redhat-io-read
        metadataPolicy: None
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: registry-redhat-io-read
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: '{"auths":{"registry.redhat.io":{"auth":"{{ .data | b64enc }}"}}}'
