---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iib-qe-pipeline
  namespace: iib-qe
  annotations:
    argocd.argoproj.io/sync-wave: "1"
secrets:
  - name: registry-proxy-push-secret
  - name: registry-redhat-io-read
imagePullSecrets:
  - name: registry-proxy-push-secret
  - name: registry-redhat-io-read
