apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redhat-appstudio-externalsecret
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: production/infrastructure/github-argocd/kflux-c-prd-i01/redhat-appstudio
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: redhat-appstudio-secret
